# Generated by Django 5.2.5 on 2025-11-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="current_passengers",
            field=models.PositiveIntegerField(
                default=0, help_text="Live passenger count reported by driver app"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="last_passenger_update",
            field=models.DateTimeField(
                blank=True,
                help_text="When driver last updated passenger count",
                null=True,
            ),
        ),
    ]
