# Generated by Django 5.2.5 on 2025-11-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_schedule_current_passengers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="current_stop_sequence",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Sequence number of the current stop in the route",
            ),
        ),
    ]
