# Generated by Django 5.2.5 on 2025-11-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demand", "0003_alter_demandalert_admin_notes_and_more"),
        ("schedules", "0004_schedule_current_stop_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_spare_trip",
            field=models.BooleanField(
                default=False,
                help_text="True if this schedule is a spare bus dispatched from a demand alert",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="source_alert",
            field=models.ForeignKey(
                blank=True,
                help_text="Demand alert that triggered this spare bus trip",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spare_schedules",
                to="demand.demandalert",
            ),
        ),
    ]
