# Generated by Django 5.2.5 on 2025-11-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demand", "0003_alter_demandalert_admin_notes_and_more"),
        ("schedules", "0005_schedule_is_spare_trip_schedule_source_alert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="is_spare_trip",
            field=models.BooleanField(
                default=False,
                help_text="True if this schedule was created as a spare bus from a demand alert.",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="source_alert",
            field=models.ForeignKey(
                blank=True,
                help_text="Demand alert that triggered this spare trip (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spare_schedules",
                to="demand.demandalert",
            ),
        ),
    ]
