# Generated by Django 5.2.5 on 2025-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_alter_schedule_is_spare_trip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="end_stop_sequence",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Last stop SEQUENCE this schedule serves (inclusive). Null = serve all stops until route's final stop.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_stop_sequence",
            field=models.PositiveIntegerField(
                default=1,
                help_text="First stop SEQUENCE this schedule actually serves (inclusive). For normal trips this is usually 1. For spare buses this can be overflow stop sequence.",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="arrival_time",
            field=models.TimeField(
                help_text="Approximate arrival at last stop for this schedule"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="departure_time",
            field=models.TimeField(
                help_text="Start time (at first stop for this schedule)"
            ),
        ),
    ]
