# Generated by Django 5.2.5 on 2025-12-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0007_schedule_end_stop_sequence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="end_stop_sequence",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="start_stop_sequence",
        ),
        migrations.AddField(
            model_name="schedule",
            name="starting_stop_sequence",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Original starting stop sequence (never changes after dispatch)",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="arrival_time",
            field=models.TimeField(help_text="Approximate arrival at destination"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="current_stop_sequence",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Sequence number of the current stop in the route (changes as bus moves)",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="departure_time",
            field=models.TimeField(help_text="Start time from origin"),
        ),
    ]
