# Generated by Django 5.2.5 on 2026-02-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_alter_route_zone"),
        ("schedules", "0008_remove_schedule_end_stop_sequence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusRouteAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                (
                    "assignment_reason",
                    models.TextField(
                        help_text="Why this bus got this route (e.g., 'Low profit last week - assigned high profit route')"
                    ),
                ),
                (
                    "expected_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedules.bus"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="routes.route"
                    ),
                ),
            ],
            options={
                "ordering": ["week_start_date", "bus"],
                "unique_together": {("bus", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="RouteProfitability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("total_trips", models.IntegerField(default=0)),
                (
                    "average_passengers_per_trip",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_profit_per_trip",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("profitability_rank", models.IntegerField(blank=True, null=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="routes.route"
                    ),
                ),
            ],
            options={
                "ordering": ["-average_profit_per_trip"],
                "unique_together": {("route", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="SpareBusSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("spare_start_time", models.TimeField()),
                ("spare_end_time", models.TimeField()),
                ("was_dispatched", models.BooleanField(default=False)),
                ("dispatch_reason", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedules.bus"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "spare_start_time"],
                "unique_together": {("bus", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyBusPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("total_trips", models.IntegerField(default=0)),
                ("total_passengers", models.IntegerField(default=0)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fuel_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("profit_rank", models.IntegerField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedules.bus"
                    ),
                ),
            ],
            options={
                "ordering": ["-total_profit"],
                "unique_together": {("bus", "week_start_date")},
            },
        ),
    ]
