# Generated by Django 5.2.5 on 2026-02-18 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0009_busrouteassignment_routeprofitability_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sparebusschedule",
            options={},
        ),
        migrations.RemoveField(
            model_name="sparebusschedule",
            name="dispatch_reason",
        ),
        migrations.RemoveField(
            model_name="sparebusschedule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="sparebusschedule",
            name="was_dispatched",
        ),
        migrations.AddField(
            model_name="sparebusschedule",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sparebusschedule",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sparebusschedule",
            name="dispatched_to_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spare_bus_dispatched",
                to="schedules.schedule",
            ),
        ),
        migrations.AddField(
            model_name="sparebusschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting (not started yet)"),
                    ("active", "Active (driver clicked Spare Mode)"),
                    ("dispatched", "Dispatched to a route"),
                    ("completed", "Spare time ended"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SpareDispatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - looking for spare bus"),
                            ("assigned", "Spare bus assigned"),
                            ("completed", "Spare bus completed the trip"),
                            ("failed", "No spare bus available"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_spare",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_requests",
                        to="schedules.sparebusschedule",
                    ),
                ),
                (
                    "original_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_requests",
                        to="schedules.schedule",
                    ),
                ),
            ],
        ),
    ]
