# Generated by Django 5.2.5 on 2026-02-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0010_alter_sparebusschedule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("covered_by_spare", "Covered by Spare"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
