# Generated by Django 5.2.5 on 2026-03-15 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_alter_route_zone"),
        ("schedules", "0011_schedule_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passenger_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of passengers on this ticket"
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boarding_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_tickets",
                        to="routes.stop",
                    ),
                ),
                (
                    "dropoff_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoff_tickets",
                        to="routes.stop",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
    ]
