# Generated by Django 5.2.5 on 2025-11-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Zone for zonal admins and drivers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="zones.zone",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("passenger", "Passenger"),
                    ("driver", "Driver"),
                    ("zonal_admin", "Zonal Admin"),
                    ("admin", "Admin"),
                ],
                default="passenger",
                help_text="User role in the system",
                max_length=20,
            ),
        ),
    ]
