# Generated by Django 5.2.5 on 2026-03-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0011_schedule_status"),
        ("users", "0002_customuser_zone_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="permanent_bus",
            field=models.ForeignKey(
                blank=True,
                help_text="The bus this driver is permanently assigned to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permanent_driver",
                to="schedules.bus",
            ),
        ),
    ]
