# Generated by Django 5.2.5 on 2025-11-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="zone",
            field=models.ForeignKey(
                help_text="Which zone controls this route",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="zones.zone",
            ),
        ),
    ]
