# Generated by Django 5.2.5 on 2025-11-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_route_zone"),
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Operational zone that manages this route",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="zones.zone",
            ),
        ),
    ]
