# Generated by Django 5.2.5 on 2025-12-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preinforms", "0002_initial"),
        ("routes", "0003_alter_route_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="preinform",
            name="dropoff_stop",
            field=models.ForeignKey(
                blank=True,
                help_text="Stop where passenger will get down",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dropoff_passengers",
                to="routes.stop",
            ),
        ),
    ]
