# Generated by Django 5.2.5 on 2026-03-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preinforms", "0003_preinform_dropoff_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preinform",
            name="status",
            field=models.CharField(
                choices=[
                    ("noted", "Noted"),
                    ("completed", "Journey Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="noted",
                help_text="Current status of pre-inform",
                max_length=20,
            ),
        ),
    ]
