# Generated by Django 5.2.5 on 2025-11-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demand", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandalert",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Notes from control room / system"
            ),
        ),
        migrations.AlterField(
            model_name="demandalert",
            name="expires_at",
            field=models.DateTimeField(
                help_text="When this alert expires (default: 1 hour from creation)"
            ),
        ),
        migrations.AlterField(
            model_name="demandalert",
            name="number_of_people",
            field=models.PositiveIntegerField(
                help_text="Approximate number of people waiting / predicted load"
            ),
        ),
        migrations.AlterField(
            model_name="demandalert",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Passenger reporting the crowd (or null for system auto-alerts)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demand_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
